include: _default_template_yaml
task: "vstar_bench_relative_position"
dataset_kwargs:
  data_files:
    test: /data/workspace/FoveaToken/data/eval/vstar-bench/data/test-*.parquet
process_docs: !function utils.vstar_filter_relative_position
metric_list:
  - metric: vstar_relative_position_acc
    aggregation: !function utils.vstar_aggregate_results
    higher_is_better: true
